name: Deploy to Production
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  deploy-prod:
    name: Deploy to Production
    uses: projet-ccm2/shared-workflows/.github/workflows/nodejs-cd.yml@main
    if: github.event_name != 'pull_request'
    with:
      required_env_vars: GCP_SA_KEY,GCP_PROJECT_ID,TWITCH_CLIENT_ID,ALLOWED_ORIGINS,DB_SERVICE_URL,REDIS_URL,CACHE_TTL,TWITCH_LISTENER_URL,TWITCH_LISTENER_API_KEY,DISCORD_NOTIF_URL
      docker-image-name: notification-handler-api-prod
      docker-tag: ${{ github.event.inputs.image-tag || format('dev-{0}', github.sha) }}
      artifact-registry-repository: "notification-handler-docker-prod"
      environment: production
      cloud-run-service-name: notification-handler-prod

    secrets:
      GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS_PROD }}
      DB_SERVICE_URL: ${{ secrets.PROD_DB_SERVICE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      CACHE_TTL: ${{ secrets.CACHE_TTL }}
      TWITCH_LISTENER_URL: ${{ secrets.PROD_TWITCH_LISTENER_URL }}
      TWITCH_LISTENER_API_KEY: ${{ secrets.TWITCH_LISTENER_API_KEY }}
      DISCORD_NOTIF_URL: ${{ secrets.PROD_DISCORD_NOTIF_URL }}
